name = "SystemBindings"
uuid = "75a07032-1394-4a60-8011-bf81691479e2"
authors = ["Keith Rutkowski <keith@analytech-solutions.com>"]
version = "0.1.0"

[deps]
CBinding = "d43a6710-96b8-4a2d-833c-c424785e5374"
CBindingGen = "308a6e0c-0495-45e1-b1ab-67fb455a0d77"

[compat]
CBinding = "^0.6"
CBindingGen = "^0.1"
julia = "^1.1"
