name = "System"
uuid = "75a07032-1394-4a60-8011-bf81691479e2"
authors = ["Keith Rutkowski <keith@analytech-solutions.com>"]
version = "0.1.0"

[deps]
CBinding = "d43a6710-96b8-4a2d-833c-c424785e5374"

[compat]
julia = "^1.5"
CBinding = "^1.0.2"
