name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.container }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.5'
          - '1.6-nightly'
          - 'nightly'
        os:
          - ubuntu-latest
        container:
          # - 'alpine:3'
          - 'amazonlinux:2'
          - 'archlinux:base'
          - 'centos:7'
          - 'centos:8'
          - 'debian:8'
          - 'debian:9'
          - 'debian:10'
          - 'fedora:34'
          # - 'opensuse/leap:15'
          - 'ubuntu:16.04'
          - 'ubuntu:18.04'
          - 'ubuntu:20.04'
        arch:
          - x64
        # include:
        #   - os: macos-latest
        #     version: '1.5'
        #     arch: x64
        #   - os: macos-latest
        #     version: '1.6-nightly'
        #     arch: x64
        #   - os: macos-latest
        #     version: 'nightly'
        #     arch: x64
        #   - os: windows-latest
        #     version: '1.5'
        #     arch: x64
        #   - os: windows-latest
        #     version: '1.6-nightly'
        #     arch: x64
        #   - os: windows-latest
        #     version: 'nightly'
        #     arch: x64
    steps:
      - name:  Install deps
        if: ${{ runner.os == 'Linux' }}
        run: |
          set -eu
          
          case "${{ matrix.container }}" in
            'debian:'* | 'ubuntu:'*)
              apt-get update
              apt-get install -y --no-install-recommends curl ca-certificates libc6-dev libasound2 libasound2-dev
              ;;
            'amazonlinux:'* | 'centos:'* | 'fedora:'*)
              yum -y install tar gzip glibc-headers alsa-lib alsa-lib-devel
              ;;
            'opensuse/leap:'*)
              zypper install -y tar gzip curl
              ;;
            'archlinux:'*)
              yes | pacman -Syu --needed alsa-lib
              ;;
            *)
              ;;
          esac
      
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
